### ISSUE TITLE
感觉某些地方可以优化一下

### ISSUE THREAD

**Issue by XueMeijing** [sytpb/chatgpt-dingtalk-robot#1]
1. 鉴权优化
  钉钉消息Header有sign timestamp两个请求头，可以用这个鉴权，可以看下这个文件 [auth](https://github.com/XueMeijing/dingtalk-chatgpt-node/blob/main/src/common/auth/auth.guard.ts) 的 checkSignature 方法，我从python版本移植过来的
2. 分组和单对单聊天模式可以优化
  其实这两个模式是同一个，请求body有 sessionWebhook 字段，往这个字段发消息就可以了，可以看下我用nestjs写的  https://github.com/XueMeijing/dingtalk-chatgpt-node

**Comment by sytpb** [comment]
谢谢你的建议， sessionWebhook 字段可以直接回复？  我一直找怎么直接回复的接口，钉钉的文档实在是没搞清楚 ， 这块文档链接能不能发下。

**Comment by XueMeijing** [comment]
> 谢谢你的建议， sessionWebhook 字段可以直接回复？ 我一直找怎么直接回复的接口，钉钉的文档实在是没搞清楚 ， 这块文档链接能不能发下。


钉钉的文档确实很难懂，我当时看还要装乱七八糟的sdk，看了这篇文章我才知道的 
 https://xie.infoq.cn/article/3340770024c49b5b1a54597d5
