### ISSUE TITLE
由于系统维护，@能力暂不可用，由此带来的不便非常抱歉。

### ISSUE THREAD

**Issue by andytai1019** [sytpb/chatgpt-dingtalk-robot#16]
与机器人对话提示由于系统维护，@能力暂不可用，由此带来的不便非常抱歉。

**Comment by andytai1019** [comment]
这怎么处理,部署好了提示这个

**Comment by sytpb** [comment]
一对一呢？

**Comment by andytai1019** [comment]
我是在机器人对话框发出讯息后提示的呢,您好群的二维码已过期可否重新提供谢谢

**Comment by sytpb** [comment]
![50d0051b19735e386a95e46587c6ebd](https://github.com/sytpb/chatgpt-dingtalk-robot/assets/12178686/9a79d325-008b-4be4-a09f-ea7316a97a82)
也可以加我的星球，最新动态或部署问题，这里可以一对一解答 。
https://t.zsxq.com/0dn2T4W94

**Comment by sytpb** [comment]
注意钉钉机器人的名称不能用chatgpt openai 等关键词，会引起此问题。
