### ISSUE TITLE
第一次部署成功后，聊了两句就自动关闭了。第二次又重新部署，部署后没有反应。

### ISSUE THREAD

**Issue by guoqikun** [sytpb/chatgpt-dingtalk-robot#2]
两次部署均不成功，

**Comment by sytpb** [comment]
是render 部署吗？ 建议用vercel 部署。 有问题把日志贴上来。

**Comment by guoqikun** [comment]
<img width="1231" alt="Snipaste_2023-05-23_14-08-18" src="https://github.com/sytpb/chatgpt-dingtalk-robot/assets/63895454/66f92def-4560-4e88-a1cd-4edb31b24825">

**Comment by guoqikun** [comment]
> 是render 部署吗？ 建议用vercel 部署。 有问题把日志贴上来。

已贴图，聊第一句话可以的，有回复，但是后面就不行了

**Comment by sytpb** [comment]
OK  504 是vercel 超时处理， vercel 免费版，请求超过10秒的，主动给断开了。 
处理办法：
1： 重发问题，取决于网络延时。 
2： 你可以在function 里选不同的区域，看哪个快
3：升级成为付费版

**Comment by guoqikun** [comment]
> OK 504 是vercel 超时处理， vercel 免费版，请求超过10秒的，主动给断开了。 处理办法： 1： 重发问题，取决于网络延时。 2： 你可以在function 里选不同的区域，看哪个快 3：升级成为付费版

谢谢，和render一样看来都要收费才稳定，😓
