### ISSUE TITLE
部署完后没效果

### ISSUE THREAD

**Issue by yizhiaoxiangdeying** [sytpb/chatgpt-dingtalk-robot#3]
调试发布后，钉钉群有弹一次消息，后面发消息就没反应了

**Comment by sytpb** [comment]
vercel 部署还是render ?  日志贴上来。

**Comment by yizhiaoxiangdeying** [comment]
在Vercel 部署的

**安装日志**
[23:15:48.577] Running build in San Francisco, USA (West) – sfo1
[23:15:48.648] Cloning github.com/yizhiaoxiangdeying/chatgpt-dingtalk-robot-1 (Branch: main, Commit: cf131a9)
[23:15:48.785] Previous build cache not available
[23:15:49.289] Cloning completed: 640.781ms
[23:15:49.475] Running "vercel build"
[23:15:50.134] Vercel CLI 29.3.6
[23:15:50.877] Warning: Detected "engines": { "node": ">=17.3.0" } in your `package.json` that will automatically upgrade when a new major Node.js Version is released. Learn More: http://vercel.link/node-version
[23:15:50.881] Installing dependencies...
[23:15:51.260] yarn install v1.22.17
[23:15:51.290] info No lockfile found.
[23:15:51.299] [1/5] Validating package.json...
[23:15:51.303] [2/5] Resolving packages...
[23:15:51.946] [3/5] Fetching packages...
[23:15:52.827] [4/5] Linking dependencies...
[23:15:53.149] [5/5] Building fresh packages...
[23:15:53.157] success Saved lockfile.
[23:15:53.163] Done in 1.91s.
[23:15:53.185] Running "yarn run vercel-build"
[23:15:53.446] yarn run v1.22.17
[23:15:53.487] $ echo hello
[23:15:53.503] hello
[23:15:53.506] Done in 0.07s.
[23:15:54.859] Build Completed in /vercel/output [4s]
[23:15:54.988] Deploying outputs...
[23:15:59.089] Deployment completed
[23:16:00.641] Uploading build cache [875.43 kB]...
[23:16:01.057] Build cache uploaded: 415.968ms

**运行日志**
MAY 26 16:22:27.49
404
chatgpt-dingtalk-robot-1-862wv9e66-yizhiaoxiangdeying.vercel.app
[GET] /
MAY 26 16:21:36.05
404
chatgpt-dingtalk-robot-1-862wv9e66-yizhiaoxiangdeying.vercel.app
[GET] /
accesstoken === ffa99672b30d36c0874b63ee1ba27b66
MAY 26 16:18:05.21
404
chatgpt-dingtalk-robot-1-862wv9e66-yizhiaoxiangdeying.vercel.app
[GET] /favicon.ico
MAY 26 16:18:03.77
404
chatgpt-dingtalk-robot-1-862wv9e66-yizhiaoxiangdeying.vercel.app
[GET] /
MAY 26 16:18:03.73
404
chatgpt-dingtalk-robot-1-862wv9e66-yizhiaoxiangdeying.vercel.app
[GET] /
MAY 26 16:13:31.12
404
chatgpt-dingtalk-robot-1-862wv9e66-yizhiaoxiangdeying.vercel.app
[GET] /

**Comment by llxx2023** [comment]
调试发布后，钉钉群有弹一次消息，后面发消息就没反应了

**Comment by sytpb** [comment]
没看到收发消息的日志，在群里聊天你@机器人了吗？

**Comment by llxx2023** [comment]
![图片](https://github.com/sytpb/chatgpt-dingtalk-robot/assets/130454446/cf4f1bf5-9f87-4ca3-8239-f78fae1e7c95)

**Comment by yizhiaoxiangdeying** [comment]
> 没看到收集发布消息的日志，在群里聊天你@机器人了吗？

![image](https://github.com/sytpb/chatgpt-dingtalk-robot/assets/73765513/85e7a7f0-cd60-46e3-af99-7dc06f30a1f3)

**Comment by sytpb** [comment]
![image](https://github.com/sytpb/chatgpt-dingtalk-robot/assets/12178686/db77c1de-c542-4636-ac91-b23eb64c1981)

发消息看下，刷出来类似这样的日志，vercel 收到你发出的消息。

**Comment by llxx2023** [comment]
嗯，是可以收到，然后紧接着就报错了

**Comment by sytpb** [comment]
200 这一列是504吗？

**Comment by yizhiaoxiangdeying** [comment]
> 200 这一列是504吗？

我这有504报错

**Comment by sytpb** [comment]
504 是网络请求超时。

**Comment by sytpb** [comment]
![image](https://github.com/sytpb/chatgpt-dingtalk-robot/assets/12178686/c8257dfc-6fd6-4105-9698-cc4cea8ce91f)

这情况我这偶尔也有，因为我们用的免费版的vercel .       按图切换一下节点试试哪个快。

**Comment by yizhiaoxiangdeying** [comment]
> ![image](https://user-images.githubusercontent.com/12178686/241178807-c8257dfc-6fd6-4105-9698-cc4cea8ce91f.png)
> 
> 这情况我这偶尔也有，因为我们用的免费版的vercel . 按图切换一下节点试试哪个快。

一个个换都是红色504

**Comment by sytpb** [comment]
你们梯子节点是哪？   把梯子关了或者切换下梯子的节点试试。

**Comment by yizhiaoxiangdeying** [comment]
> 你们梯子节点是哪？ 把梯子关了或者切换下梯子的节点试试。

手机没有挂梯子发的消息 会不会是gpt对服务器的ip封锁

**Comment by sytpb** [comment]
是不是用的Vercel 生成的域名？ 没有绑自己的域名吧？

**Comment by yizhiaoxiangdeying** [comment]
> 是不是用的Vercel 生成的域名？ 没有绑自己的域名吧？

绑了自己的域名，解析都做了
![image](https://github.com/sytpb/chatgpt-dingtalk-robot/assets/73765513/777a87cf-5ef9-48dc-99c7-16677dc25a32)

**Comment by sytpb** [comment]
手机不挂梯子没有问题，那在电脑上试试吧。 一个消息也没回复吗？ 除了第一条。很奇怪。

**Comment by sytpb** [comment]
把日志展开，看下具体返回了什么？

**Comment by yizhiaoxiangdeying** [comment]
> 手机不挂梯子没有问题，那在电脑上试试吧。 一个消息也没回复吗？ 除了第一条。很奇怪。

屁都不放一个 服了
![image](https://github.com/sytpb/chatgpt-dingtalk-robot/assets/73765513/b20b5a20-ee6f-4649-8e21-77c7af93fb8a)

![image](https://github.com/sytpb/chatgpt-dingtalk-robot/assets/73765513/71c91bf9-23ae-4a08-a5be-2b838620f8d8)

**Comment by sytpb** [comment]
日志看右下角，openai 报错了，参数配置有问题。

**Comment by yizhiaoxiangdeying** [comment]
> 



> 日志看右下角，openai 报错了，参数配置有问题。

open aipkey问题？ 还是端口问题？端口用的你教程的7070，其他的应该都没问题 部署过好几次了，之前用第二个办法部署也是这样，这回第一个方法也是

**Comment by sytpb** [comment]
![image](https://github.com/sytpb/chatgpt-dingtalk-robot/assets/12178686/856ab33f-f704-4c23-837c-a3a37b2b1397)

端口没有问题，有问题配置消息那一步都过不了。 主要检查这两项，是否配对了，另外api_key 没有过期吗？

**Comment by sytpb** [comment]
值前后不要多加空格。

**Comment by yizhiaoxiangdeying** [comment]
> 值前后不要多加空格。
检查过空格没问题，api_key 每次都是新申请的值，刚刚创建了新值也是一样，整不活，一样的错误。不会就我有这样的问题吧

**Comment by sytpb** [comment]
个别这个问题，都是配置出错。 

Usage 里，看下 有没有到期？
![image](https://github.com/sytpb/chatgpt-dingtalk-robot/assets/12178686/848c2cb4-0aae-4197-a1ad-6822957ccc5b)

在微信群里吗？

**Comment by yizhiaoxiangdeying** [comment]
> 个别这个问题，都是配置出错。
> 
> Usage 里，看下 有没有到期？ ![image](https://user-images.githubusercontent.com/12178686/241210278-848c2cb4-0aae-4197-a1ad-6822957ccc5b.png)
> 
> 在微信群里吗？

没找到那个地方，刚注册的没这么快过期吧，钉钉的群加不了，加了企业微信 群

**Comment by sytpb** [comment]
加我微信我看下。

**Comment by llxx2023** [comment]
怎么进群

**Comment by sytpb** [comment]
error: {
        message: 'You exceeded your current quota, please check your plan and billing details.',
        type: 'insufficient_quota',
        param: null,
        code: null
      }

![818ce68af255e9cc22b55fe9c8aea30](https://github.com/sytpb/chatgpt-dingtalk-robot/assets/12178686/6e0be183-a7e4-4683-a088-11207791dcf2)

https://stackoverflow.com/questions/75898276/openai-chatgpt-gpt-3-5-api-error-429-you-exceeded-your-current-quota-please

这种情况是配额用完了或者到期了，或者请求数量太多被限制了，前两者情况需要充值才可以， 第三个情况，过一段时间会恢复。

**Comment by sytpb** [comment]
![cc1d5853cde0f5ec5af61e0c2636df6](https://github.com/sytpb/chatgpt-dingtalk-robot/assets/12178686/4db917a5-7dda-4745-a9b4-a6e46966baeb)
@llxx2023

**Comment by sytpb** [comment]
![0e9a8259a30004cefdb4896748c18e0](https://github.com/sytpb/chatgpt-dingtalk-robot/assets/12178686/4202e8fa-39c6-42f3-9948-b4fcc13c1398)

红色代表已过期
