### ISSUE TITLE
添加api代理地址

### ISSUE THREAD

**Issue by zyjia** [sytpb/chatgpt-dingtalk-robot#5]
This Serverless Function has crashed.

Your connection is working correctly.

Vercel is working correctly.

500: INTERNAL_SERVER_ERROR

我用的是azure的api,是否可以支持一下设置代理api地址，而不是默认的官方地址？

**Comment by sytpb** [comment]
代理api 地址，是说支持azure 吗？  azure 你申请下来了？

**Comment by zyjia** [comment]
> 代理api 地址，是说支持azure 吗？ azure 你申请下来了？

我有azure的api,我用的是https://github.com/stulzq/azure-openai-proxy这个项目的代理,它可以完全仿真openai的api,或者参考一下ios上的app如opencat/chatx/问天等的实现方式这样对用户更友好。

**Comment by sytpb** [comment]
azure openai 接口是收费的，这个项目免费给大家用？

**Comment by zyjia** [comment]
> azure openai 接口是收费的，这个项目免费给大家用？

这不是自己部署，自己填参数吗？

**Comment by sytpb** [comment]
> 这不是自己部署，自己填参数吗？

是的，但是你得申请到Azure  openai 的key .
