### ISSUE TITLE
日志反馈错误

### ISSUE THREAD

**Issue by Eason-open** [sytpb/chatgpt-dingtalk-robot#7]
Jun 12 11:24:13 PM  [ { role: 'user', content: ' 。。。' } ]
Jun 12 11:24:14 PM  OpenAI happen error!
Jun 12 11:24:14 PM  undefined
Jun 12 11:24:14 PM  <text.js:97> undefined

所有设置都按照教程进行，日志反馈错误，是什么原因呢

**Comment by sytpb** [comment]
https://github.com/sytpb/chatgpt-wework-robot/issues/13  参见这里
