### ISSUE TITLE
请问大佬 这个项目不会关联上下文吗

### ISSUE THREAD

**Issue by Timoshao** [sytpb/chatgpt-dingtalk-robot#9]
![image](https://github.com/sytpb/chatgpt-dingtalk-robot/assets/108260847/8373a5c1-82af-40b5-ae18-6e143bd75991)

**Comment by sytpb** [comment]
![image](https://github.com/sytpb/chatgpt-dingtalk-robot/assets/12178686/a254bdcc-d73e-4dd2-a91d-e154c26c2452)
